language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: k4cxDFyk7Tumvxw48us31+oShpuDEkO2PWW8CXo+SAOKr18QAQjsBecFxnURKF377chK5s46PEc1HC54e5LpiXUK2gEzyophnGMO8lBr7xABxKO6uuyUOqGEVaJW/PsMcvLxYk6iuTfvYvxiouPLtSC1VuS5UBYYPYhEpWE6oUU=
  app:
    master: kshsn-bot
  on:
    repo: succi0303/myhubot
  run:
    - restart
notifications:
  webhooks:
    - https://kshsn-bot.herokuapp.com/travisci/webhook_notification
  on_start: true
